// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfyz3GfYhdQBS7D_yjnyM4G6N56_HGA-E',
    appId: '1:1006929727809:web:441925b37ad1ac2d1951c0',
    messagingSenderId: '1006929727809',
    projectId: 'ia-pour-le-mobile',
    authDomain: 'ia-pour-le-mobile.firebaseapp.com',
    storageBucket: 'ia-pour-le-mobile.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvEtPRySr0L8Vz3ZB3emTX3h4mlqL1BNU',
    appId: '1:1006929727809:android:94ab91cf2755969a1951c0',
    messagingSenderId: '1006929727809',
    projectId: 'ia-pour-le-mobile',
    storageBucket: 'ia-pour-le-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQMsfI2Rxn-beZv5KSB2UkWFTXbo7K-jY',
    appId: '1:1006929727809:ios:3b37067bf5605f851951c0',
    messagingSenderId: '1006929727809',
    projectId: 'ia-pour-le-mobile',
    storageBucket: 'ia-pour-le-mobile.appspot.com',
    iosBundleId: 'com.example.iaPourLeMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQMsfI2Rxn-beZv5KSB2UkWFTXbo7K-jY',
    appId: '1:1006929727809:ios:1a1acd06f000c5301951c0',
    messagingSenderId: '1006929727809',
    projectId: 'ia-pour-le-mobile',
    storageBucket: 'ia-pour-le-mobile.appspot.com',
    iosBundleId: 'com.example.iaPourLeMobile.RunnerTests',
  );
}
